#!/bin/sh
# goal.yaml — seed only on first boot (user config, never overwrite)
if [ ! -f /app/state/goal.yaml ]; then
    cp /app/defaults/goal.yaml /app/state/goal.yaml
fi

# strategy.yaml — always sync from image on every deploy
# Hermes updates this file in git → Railway redeploys → this copies the new version
cp /app/defaults/strategy.yaml /app/state/strategy.yaml

mkdir -p /app/state/history

# One-time migration: clear trades generated by old immediate-exit logic
if [ ! -f /app/state/.trades_v2_migrated ]; then
    > /app/state/trades.jsonl
    rm -f /app/state/position.json
    touch /app/state/.trades_v2_migrated
fi

exec "$@"
