#!/bin/sh
# Seed /app/state from /app/defaults on first boot (volume starts empty)
for f in /app/defaults/*; do
    dest="/app/state/$(basename "$f")"
    if [ ! -f "$dest" ]; then
        cp "$f" "$dest"
    fi
done
mkdir -p /app/state/history

# One-time migration: clear trades generated by old immediate-exit logic
if [ ! -f /app/state/.trades_v2_migrated ]; then
    > /app/state/trades.jsonl
    rm -f /app/state/position.json
    touch /app/state/.trades_v2_migrated
fi

exec "$@"
